# Generated by Django 4.2.2 on 2023-06-27 09:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cv", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="education",
            name="end_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="experience",
            name="end_date",
            field=models.DateField(null=True),
        ),
    ]
