# Generated by Django 4.2.2 on 2023-06-27 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cv", "0003_education_city_education_country_experience_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="education",
            name="level",
            field=models.CharField(
                choices=[
                    ("High School", "High School"),
                    ("College", "College"),
                    ("University", "University"),
                    ("Other", "Other"),
                ],
                max_length=16,
            ),
        ),
    ]
